### PR TITLE
Added automatic static data extraction.

### PR DESCRIPTION
**Pull request by SteveJRose**
Added the Il2CppDumper project as a submodule. Use that to extract the data previously done in the python util. Cached data is stored in the registry and updates when the version changes or when a checkbox in the GUI is checked.

### CODE REVIEW

**Comment by LukeCroteau** [comment]
This is an interesting PR. I don't know how I feel about it.
I like not having to run a script to update memory addresses and field information.
I don't like having to distribute il2cppdumper to end users running the extractor.

**Review by LukeCroteau — APPROVED** [review]
Changes look fine.

**Comment by SteveJRose** [comment]
> This is an interesting PR. I don't know how I feel about it.
> I like not having to run a script to update memory addresses and field information.
> I don't like having to distribute il2cppdumper to end users running the extractor.

I see your point, if you want I could implement a dual system so that the old way still works.

**Comment by LukeCroteau** [comment]
> I see your point, if you want I could implement a dual system so that the old way still works.

What if we left this code in here for us Devs, maybe accessible via commandline or keystroke.
For end users, allow the dev/pipeline that prepares the release to dump the addresses to a Json file, similar to how we're currently handling Champ information.
End users would get the distributed addresses loaded in via the static handler, but wouldn't need to have il2cppdumper?
This was more along the lines of what I was going to do, to eventually replace the Python script, so that we could have better automated building.

**Comment by LukeCroteau** [comment]
I do also want to say, Fantastic thought, and I truly appreciate it.

If you need any support from me, just let me know. I'm willing to chip in and collab if needed!

**Comment by SteveJRose** [comment]
> > I see your point, if you want I could implement a dual system so that the old way still works.
> 
> What if we left this code in here for us Devs, maybe accessible via commandline or keystroke.
> For end users, allow the dev/pipeline that prepares the release to dump the addresses to a Json file, similar to how we're currently handling Champ information.
> End users would get the distributed addresses loaded in via the static handler, but wouldn't need to have il2cppdumper?
> This was more along the lines of what I was going to do, to eventually replace the Python script, so that we could have better automated building.

I'll look into getting that done then. I did consider adding my own code to handle the il2cpp parsing, but decided it would probably just end up being a copy of Il2CppDumper, which I didn't want to do.

**Comment by LukeCroteau** [comment]
> I'll look into getting that done then. I did consider adding my own code to handle the il2cpp parsing, but decided it would probably just end up being a copy of Il2CppDumper, which I didn't want to do.

I agree that we definitely don't want that.
I was pointed to a fork of IL2CppDumper by someone running a different project, that dumped out json as output.
It was on my "todo list" to look and see if I could make a nice thing using that, instead of the python script.
All towards the end of making this more automatable, and extendable, obviously, just like you're doing.

**Review by LukeCroteau — APPROVED** [review]
Yeah! This is what we were looking for, I think!

**Comment by LukeCroteau** [comment]
Adding a comment that it looks like this should push #7 out of the way as we move towards a more automated pipeline, with minimal required commits. Love it! Thanks!

**Comment by LukeCroteau** [comment]
@SteveJRose Do you mind fixing up the conflicts, and I'll merge this in (finally!)?

I think it's just keeping data out of the RaidStaticInformation.cs but I'd just like you to take 1 more look at it and see if you're happy with this still.

**Comment by SteveJRose** [comment]
> @SteveJRose Do you mind fixing up the conflicts, and I'll merge this in (finally!)?
> 
> I think it's just keeping data out of the RaidStaticInformation.cs but I'd just like you to take 1 more look at it and see if you're happy with this still.

No problem, I'll get onto it as soon as I can.

**Comment by SteveJRose** [comment]
Conflicts fixed, data values added for new version.

**Review by LukeCroteau — APPROVED** [review]

**Pull request merged**
